# Generated by Django 4.1.1 on 2022-11-01 07:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('title', models.CharField(max_length=25)),
                ('debate_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_created', models.DateTimeField(blank=True, null=True)),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_ended', models.DateTimeField(blank=True, null=True)),
                ('privacy_status', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public')], max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('news_article_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('body', models.TextField(max_length=99)),
                ('time_created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('participant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Host', 'Host'), ('Guest', 'Guest')], max_length=30, null=True)),
                ('time_joined', models.DateTimeField(blank=True, null=True)),
                ('time_left', models.DateTimeField(blank=True, null=True)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_participant', to='socialapp.debate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particiant_debate', to='socialapp.debate')),
            ],
        ),
        migrations.AddField(
            model_name='debate',
            name='news_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debate_article', to='socialapp.newsarticle'),
        ),
    ]
