# Generated by Django 4.1.1 on 2022-11-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debate',
            old_name='privacy_status',
            new_name='debate_status',
        ),
    ]
