# Generated by Django 4.1.1 on 2022-11-01 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_rename_privacy_status_debate_debate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='debate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particiant_debate', to='socialapp.debate'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_user', to='socialapp.user'),
        ),
    ]
